### ISSUE TITLE
docs: finish pages marked as TODO

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/at4j#98]
**Is your feature request related to a problem? Please describe.**

There are several pages in the documentation that contain TODOs. These need to be completed to provide comprehensive information to the users.
### Details
The following pages contain TODOs:

1. `docs/src/essential/error-handling.md` - More information about error handling in AT4J is needed.
2. `docs/src/azure-reference/datacenter-list.md` - A list of Azure datacenters and their locations is required.
3. `docs/src/advanced/caching.md` - More information about caching for AT4J is needed.

### Tasks
- [ ] Complete the error handling page with relevant information.
- [ ] Create a list of Azure datacenters and their locations.
- [ ] Complete the caching page with relevant information.
